// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace itvidpradotnetcoreadvanced.Models;

public partial class User
{
    public int UserId { get; set; }

    public string FirstName { get; set; }

    public string MiddleName { get; set; }

    public string LastName { get; set; }

    public string Dob { get; set; }

    public int? MobileNo { get; set; }

    public string Email { get; set; }

    public string Address { get; set; }

    public virtual ICollection<UserRole> UserRoles { get; set; } = new List<UserRole>();
}