// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace itvidpradotnetcoreadvanced.Models;

public partial class UserLogin
{
    public int UserId { get; set; }

    public string UserName { get; set; }

    [DataType(DataType.Password)]
    public string Password { get; set; }

    public DateTime? CreatedDate { get; set; }

    public DateTime? ModifiedDate { get; set; }

    public DateTime? LastLoginDate { get; set; }
}